# ~/.bashrc
#
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias ll='ls -alh --color=auto'
PS1='[\u@\h \W]\$ '

eval "$(starship init bash)"
export STARSHIP_CONFIG=~/.config/starship/starship.toml
export STARSHIP_CACHE=~/.starship/cache

# Alias Lenovo Vantage CLI
alias svantage='vantage-cli status'
alias vantage='sudo vantage-cli conservation'

# My Custom Alias
alias clr='clear'
alias ff='fastfetch'
alias battery='fastfetch | grep "Battery (L20M2PF0)"'
alias ram='fastfetch | grep "Memory"'
alias online='fastfetch | grep "Uptime"'
alias hmdr='cd ~'
alias cd='z'
alias lgit='lazygit'
alias rm='rm -i'
alias ip='ip -br addr'

# --- caido ---
alias caido='cd /home/apple/caido-desktop-x64-linux && ./caido'

# --- trash-cli ---
alias trash='trash-put'
alias list-trash='trash-list'
alias restore-trash='trash-restore'
alias empty-trash='trash-empty'

# --- bat ---
alias pbat='bat -p'
alias bat='bat -pn'
alias cat='pbat'

# Set up fzf key bindings and fuzzy completion
eval "$(fzf --bash)"

# Setup zoxide
eval "$(zoxide init bash)"

# Setup Yazi
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	IFS= read -r -d '' cwd <"$tmp"
	[ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
	rm -f -- "$tmp"
}

rfkill unblock all
